### ISSUE TITLE
can i request for different website. but simmilar strawpoll

### ISSUE THREAD

**Issue by creonizer1** [aaaaa289/strawpoll-bot#2]
sir. can i request for pollingkita.com. please contact me at **************
i'll give you some money if this success. thank u

**Comment by creonizer1** [comment]
please reply immediately if you read this

**Comment by popohet** [comment]
sorry for taking too long to answer. I did take a look at it, I _probably_ can do it. I do this kind of thing for fun, not for money. If you still wan't it, just reply me here and i'll _probably_ make it

**Comment by creonizer1** [comment]
> sorry for taking too long to answer. I did take a look at it, I _probably_ can do it. I do this kind of thing for fun, not for money. If you still wan't it, just reply me here and i'll _probably_ make it

of course I want. I hope you can make it.have fun mr. popohet

**Comment by d1amonds** [comment]
can you make this for strawpoll.com please?
