### ISSUE TITLE
Similar site

### ISSUE THREAD

**Issue by Fahad15a** [aaaaa289/strawpoll-bot#6]
Hello, i have same as others in this section,
I already did everything but i found out my site is different it’s (strawpoll.com) not (strawpoll.me), so maybe you’ve did it before or you know how to do it since they are similar 
If you already did send me the link please
Regards

**Comment by aaaaa289** [comment]
Strawpoll.com is much much harder to break. I'll take a look, but I cant promise anything, sorry.
